package com.vayl.identityAccess.core.domain.common.DomainException;

public enum ExceptionReason {
  // field configuration error msg
  INVALID_FIELD_CONFIG_ID,
  INVALID_FIELD_CONFIG_TYPE,
  INVALID_ENFORCEMENT_DATE,
  INVALID_VERIFICATION_REQUIREMENT,

  // permission error msg
  INVALID_PERMISSION_ID,
  INVALID_PERMISSION_NAME,

  // role error msg
  INVALID_ROLE_ID,
  INVALID_ROLE_NAME,
  UNPROCESSABLE_PERMISSION_BELONG_TO_DIFFERENT_API,
  UNPROCESSABLE_CANNOT_REMOVE_UNASSIGNED_PERMISSION,

  // Api error msg
  INVALID_API_ID,
  INVALID_API_NAME,

  // license error msg
  INVALID_LICENSE_ID,
  INVALID_LICENSE_NAME,

  // license contract error msg
  INVALID_LICENSE_CONTRACT_ID,
  INVALID_AMOUNT_ALLOCATED,
  INVALID_AMOUNT_REMAINING,
  INVALID_EXPIRY_DATE,
  INVALID_ADDITIONAL_AMOUNT,

  // organization error msg
  INVALID_ORG_ID,

  // OU error msg
  INVALID_OU_ID,
  INVALID_OU_NAME,
  INVALID_AUTHORIZATION_POLICY,
  INVALID_AUTHENTICATION_POLICY,
  INVALID_MFA_POLICY,
  INVALID_RECOVERY_POLICY,
  UNAUTHORIZED_ACCESS_TO_LICENSE_CONTRACT,
  UNAUTHORIZED_ACCESS_TO_OU,
  UNAUTHORIZED_ACCESS_TO_ROLE,
  INVALID_SHOULD_INHERIT_AUTHORIZATION_POLICY,
  INVALID_SHOULD_INHERIT_AUTHENTICATION_POLICY,
  UNPROCESSABLE_CHILD_AND_PARENT_ARE_THE_SAME,
  UNPROCESSABLE_CANNOT_ASSIGN_PARENT_TO_OU,
  UNPROCESSABLE_CANNOT_ASSIGN_TOP_LEVEL_TO_OU,
  UNPROCESSABLE_MUST_SYNCHRONIZE_WITH_PARENT,
  INVALID_MFA_TYPE,
  INVALID_MFA_ENFORCEMENT_DATE,
  INVALID_AUTHENTICATION_POLICY_INHERITANCE,
  INVALID_AUTHORIZATION_POLICY_INHERITANCE,

  // Field specific invalid reasons
  INVALID_DATE,
  INVALID_PHONE_NUMBER,
  INVALID_EMAIL,
  INVALID_ADDRESS,
  INVALID_INTEGER,
  INVALID_USERNAME,
  INVALID_STRING,
  INVALID_SCHEDULE,
  INVALID_PASSCODE
}
