package com.vayl.identityAccess.core.domain.common.DomainException;

public enum ExceptionReason {
  INVALID_ORG_ARG,
  INVALID_REG_SESSION_ARG,
  BLANK_NAME_IN_FIELD_ENTRY,
  INVALID_PERMISSION_ARG,
  INVALID_ROLE_ARG,
  INVALID_API_ARG,
  INVALID_FIELD_CONFIG_ARG,
  INVALID_LICENSE_ARG,
  INVALID_LICENSE_CONTRACT_ARG,
  INVALID_OU_ARG,

  // Field specific invalid reasons
  INVALID_DATE_INPUT,
  INVALID_PHONE_NUMBER_INPUT,
  INVALID_EMAIL_INPUT,
  INVALID_ADDRESS_INPUT,
  INVALID_INTEGER_INPUT,
  INVALID_USERNAME_INPUT,
  INVALID_STRING_INPUT,
  INVALID_PASSCODE
}
