package com.vayl.identityAccess.core.domain.common.DomainErrors;

public enum ExceptionReason {
  INVALID_ID,
  INVALID_DATE_FORMAT,
  INVALID_FIELD_TYPE,
  PRIMARY_EMAIL_ENFORCEMENT_DATE_CANNOT_BE_CHANGED,
  BLANK_PERMISSION_NAME_PROVIDED,
  GRANTED_PERMISSION_NOT_LOCATED_IN_API,
  REMOVING_UNASSIGNED_PERMISSION,
  OU_NOT_ASSIGNED_TO_PARENT,
  LICENSE_AND_OU_ORG_CONFLICT,
  ROLES_AND_OU_ORG_CONFLICT,
  ASSIGNING_TOP_LEVEL_OU_TO_PARENT,
  LICENSE_RESTRICTION_REGISTRY_NOT_INITIALIZED,
  LICENSE_RESTRICTION_REGISTRY_NOT_PROVIDED,
  ACCESS_DENIED_TO_RESTRICTABLE_BY_LICENSE_RESTRICTION_REGISTRY,
  INVALID_LICENSE_RESTRICTION_KEY,
  PARENT_AND_CHILD_ORG_CONFLICT,
  ASSIGNING_PARENT_TO_CHILD,
  ASSIGNING_SELF

}
