package com.vayl.identityAccess.core.domain.common.DomainErrors;

public enum ExceptionReason {
    INVALID_ID,
    INVALID_DATE_FORMAT,
    INVALID_FIELD_TYPE,
    PRIMARY_EMAIL_ENFORCEMENT_DATE_CANNOT_BE_CHANGED,
    BLANK_PERMISSION_NAME_PROVIDED,
    GRANTED_PERMISSION_NOT_LOCATED_IN_API,
    SELECTED_PERMISSION_NOT_GRANTED_BY_SUBSCRIPTION,
    SUBSCRIPTION_NOT_ASSIGNED

}
