package com.vayl.identityAccess.core.domain.common.DomainErrors;

public enum ExceptionEvent {
    API_ID_CREATION,
    DATE_CREATION,
    FIELD_CONFIG_ID_CREATION,
    UNVERIFIABLE_FIELD_CONFIG_CREATION,
    VERIFIABLE_FIELD_CONFIG_CREATION,
    VERIFIABLE_FIELD_CONFIG_MODIFICATION,
    PERMISSION_ID_CREATION,
    DEFAULT_ROLE_CREATION,
    DEFAULT_ROLE_PERMISSION_MODIFICATION,
    ROLE_ID_CREATION,
    SUBSCRIPTION_ID_CREATION,
    ORG_ID_CREATION,
    OU_ID_CREATION,
    OU_ASSIGNMENT,
    CHECKING_ACCESS_TO_LICENSE_RESTRICTABLE,
    UPDATING_AUTHORIZATION_POLICY
}
