package com.vayl.identityAccess.core.domain.common.DomainErrors;

public enum ExceptionEvent {
    API_ID_CREATION,
    DATE_CREATION,
    FIELDCONFIG_ID_CREATION,
    UNVERIFIABLEFIELDCONFIG_CREATION,
    VERIFIABLEFIELDCONFIG_CREATION,
    VERIFIABLEFIELDCONFIG_MODIFICATION,
    PERMISSION_ID_CREATION,
    DEFAULT_ROLE_CREATION,
    DEFAULT_ROLE_PERMISSION_MODIFICATION,
    ROLE_ID_CREATION,
    SUBSCRIPTION_ID_CREATION,
    ORG_ID_CREATION
}
