package com.vayl.identityAccess.core.application;

public enum ExceptionEvent {
  API_ID_CREATION,
  DATE_CREATION,
  FIELD_CONFIG_CREATION,
  UNVERIFIABLE_FIELD_CONFIG_CREATION,
  VERIFIABLE_FIELD_CONFIG_CREATION,
  VERIFIABLE_FIELD_CONFIG_MODIFICATION,
  PERMISSION_ID_CREATION,
  DEFAULT_ROLE_CREATION,
  CUSTOM_ROLE_CREATION,
  DEFAULT_ROLE_PERMISSION_MODIFICATION,
  CUSTOM_ROLE_PERMISSION_MODIFICATION,
  ROLE_ID_CREATION,
  LICENSE_ID_CREATION,
  ORG_ID_CREATION,
  OU_ID_CREATION,
  REG_SESSION_CREATION,
  FIELD_ENTRY_CREATION,
  REGISTRATION_SESSION_CREATION,
  OU_ASSIGNMENT,
  CHECKING_ACCESS_TO_LICENSE_RESTRICTABLE,
  UPDATING_AUTHORIZATION_POLICY,
  REMOVING_LICENSE_RESTRICTION,
  FIELD_CONFIG_MODIFICATION, API_CREATION, ROLE_CREATION, ROLE_MODIFICATION, SYNCHRONIZING_OU_WITH_PARENT
}
